version: '3'

services:
    hephaestus-r:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${JPORT:-8888}:${JPORT:-8888}"
        volumes:
            - .:/home
        command: jupyter lab --ip='*' --port=${JPORT:-8888} --no-browser --allow-root --notebook-dir=/home